class Consts(object):
    ACCESS_TOKEN = 'access_token'
    API = 'api:* member-of-groups:*'
    API_PING = '/artifactory/api/system/ping'
    API_SECURITY_TOKEN = '/artifactory/api/security/token'
    API_STORAGE_INFO = '/artifactory/api/storageinfo'
    API_USERS = '/artifactory/api/security/users/'
    API_VERSION = '/artifactory/api/system/version'
    CLI_TOKEN = 'CLI_TOKEN'
    EMAIL = 'email'
    JFROG_HOSTNAME = 'JFROG_HOSTNAME'
    HTTPS = 'https://'
    JFROG_HOSTNAME_SUFFIX = '.jfrog.io'
    JFROG_USER = 'JFROG_USER'
    LOGIN = 'login'
    NAME = 'name'
    SCOPE = 'scope'
    PASSWORD = 'password'
    PING = 'ping'
    USERNAME = 'username'
    SERVERNAME = 'servername'
    TOKEN_FILE_NAME = 'token_file.txt'


